

server:
  port: 7001


eureka:
  client:
    register-with-eureka: false #指示该eureka client客户端是否将自己注册到eureka server服务器
    fetch-registry: false #指示该eureka client客户端是否从eureka server服务器去拉取列表信息
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: cart.mall.com
    #prefer-ip-address: true  #eureka客户端写
    lease-expiration-duration-in-seconds: 90 #eureka server 在90秒之内没有收到client发送的心跳则会将实例剔除，但开启了自我保护机制，则不会剔除实例
  server:
    enable-self-preservation: true
