# 服务端口
server:
  port: 8002

# 服务名
spring:
  # 环境设置：dev、test、prod
  profiles:
    active: dev
  application:
    name: xueyuan-videoservice

  servlet:
    multipart:
      max-file-size: -1 #单个文件的最大容量无限制
      max-request-size: -1 #单个请求文件的最大容量无限制

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://cart.mall.com:7001/eureka/  #指定注册中心地址
  instance:
    prefer-ip-address: true #eureka服务器上获取的是服务器的ip地址，否则是主机名

#阿里云 OSS
#不同的服务器，地址不同
aliyun:
  oss:
    file:
      keyid: LTAI4FtCKkjGq42FioKJxuCr
      keysecret: 67J3fNKVRahsU9XoS8w9V2pWxSStUM